frontend:
  replicaCount: 2
  image:
    repository: us-west1-docker.pkg.dev/savvy-fountain-448721-d1/hello-repo/my-app
    tag: latest

backend:
  replicaCount: 2
  image:
    repository: node
    tag: 14
  env:
    DATABASE_URL: "postgres://user:password@postgres:5432/mydb"

database:
  postgresql:
    postgresqlUsername: user
    postgresqlPassword: password
    postgresqlDatabase: mydb

service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80

