
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_USER
              value: "{{ .Values.postgres.env.POSTGRES_USER }}"
            - name: DB_PASSWORD
              value: "{{ .Values.postgres.env.POSTGRES_PASSWORD }}"
            - name: DB_NAME
              value: "{{ .Values.postgres.env.POSTGRES_DB }}"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.backend.service.port }}
